//error
export const SETERROR = "SETERROR";
export const CLEARERROR = "CLEARERROR";

//auth
export const SETAUTH = "SETAUTH";
export const CLEARAUTH = "CLEARAUTH";

//loading
export const ISCATEGORYFETCHING = "ISCATEGORYFETCHING";
export const ISSUBCATEGORYFETCHING = "ISSUBCATEGORYFETCHING";
export const ISFEATUREFETCHING = "ISFEATUREFETCHING";
export const ISPRODUCTFETCHING = "ISPRODUCTFETCHING";

//category
export const FETCHCATEGORY = "FETCHCATEGORY";
export const FETCHSUBCATEGORY = "FETCHSUBCATEGORY";
export const FETCHFEATURE = "FETCHFEATURE";

export const FETCHPRODUCT = "FETCHPRODUCT";

export const SETMODALCATEGORYITEM = "SETCATEGORYITEM";
export const SETMODALFEATUREITEM = "SETMODALFEATUREITEM;";
export const SETMODALSUBCATEGORYITEM = "SETMODALSUBCATEGORYITEM";
export const SETMODALPRODUCTITEM = "SETMODALPRODUCTITEM";

export const ISUSERFETCHING = "ISUSERFETCHING";
export const FETCHUSER = "FETCHUSER";
export const SETMODALUSERITEM = "SETUSERITEM";

